### ISSUE TITLE
Parse error.

### ISSUE THREAD

**Issue by MicahZoltu** [guybedford/es-module-shims#43]
I just updated to es-module-shims 0.3.0 and am now getting the following error in the console in Firefox.

> Error: Parse error at 22373. 2 es-module-shims.js:199:365
> Error: Parse error at 6318. 2 es-module-shims.js:199:365
> Error: Parse error at 4599. es-module-shims.js:199:365

My page is not loading properly, though I do see all of the right files being fetched from the server (including name mapped files).

**Comment by MicahZoltu** [comment]
Similar error in Chrome:
```
es-module-shims.js:199 Uncaught (in promise) Error: Parse error at 22373.
    at parse (es-module-shims.js:199)
    at es-module-shims.js:424
es-module-shims.js:199 Uncaught (in promise) Error: Parse error at 22373.
    at parse (es-module-shims.js:199)
    at es-module-shims.js:424
es-module-shims.js:199 Uncaught (in promise) Error: Parse error at 4617.
    at parse (es-module-shims.js:199)
    at es-module-shims.js:424
es-module-shims.js:199 Uncaught (in promise) Error: Parse error at 4617.
    at parse (es-module-shims.js:199)
    at es-module-shims.js:424
es-module-shims.js:199 Uncaught (in promise) Error: Parse error at 6300.
    at parse (es-module-shims.js:199)
    at es-module-shims.js:424
```

**Comment by MicahZoltu** [comment]
I'm struggling to create a repro case.  A very simple website doesn't suffer the problem, but my app does.  Everything works with 0.2.7 in my project though.

**Comment by MicahZoltu** [comment]
Simplest reproduction I can come up with.  Sorry for the library import, I'm not sure what it is about that library that es-module-shims isn't liking, but importing it causes an error.  I am receiving similar errors with my other ES library imports, all of which (possibly unrelated to this issue) are compiled to `esnext` from TypeScript.
```
npm install @zoltu/ethereum-types
```
`index.html`
```html
<script type='module' src='node_modules/es-module-shims/dist/es-module-shims.js'></script>
<script type='importmap-shim'>
	{ "imports": { "@zoltu/ethereum-types": "node_modules/@zoltu/ethereum-types/output-es/index.js" } }
</script>
<script type='module-shim'>
	import '@zoltu/ethereum-types'
</script>
```
